apiVersion: apps/v1
kind: Deployment
metadata:
  name: micro-users
spec:
  replicas: 1
  selector:
    matchLabels:
      app: micro-users
  template:
    metadata:
      labels:
        app: micro-users
    spec:
      containers:
      - name: micro-users
        image: gcr.io/micro-users/micro-users-app:v1
        ports:
        - containerPort: 3000
        env:
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: jwt_secret
        - name: HASH_SALT_ROUNDS
          value: "10"
        - name: DB_HOST
          value: "mysql"
        - name: DB_PORT
          value: "3306"
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: db_username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: db_password
        - name: DB_DATABASE
          value: "users_service"
        - name: MAIL_HOST
          value: "smtp.gmail.com"
        - name: MAIL_PORT
          value: "587"
        - name: MAIL_USER
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: mail_user
        - name: MAIL_PASS
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: mail_pass
        - name: MAIL_FROM
          value: "soygokussjdios@gmail.com"
        - name: FRONTEND_URL
          value: "frontend.com"
